load("@aspect_rules_js//npm:defs.bzl", "npm_package")
load("@rules_rust//rust:rust_shared_library.bzl", "rust_shared_library")
load("@rules_rust//rust:rust_test.bzl", "rust_test")
load("@rules_rust_wasm_bindgen//:defs.bzl", "rust_wasm_bindgen")

rust_shared_library(
    name = "transpiler",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "@crates//:peg",
        "@crates//:wasm-bindgen",
    ],
)

rust_test(
    name = "test",
    compile_data = glob(["samples/**/*.s"]),
    crate = "transpiler",
)

rust_wasm_bindgen(
    name = "wasm",
    wasm_file = ":transpiler",
)

npm_package(
    name = "pkg",
    srcs = [
        "package.json",
        ":wasm",
    ],
    root_paths = [
        package_name(),
        package_name() + "/wasm",
    ],
)
